









dataset_file: datasets.toy_1d
output_path: 'logs/'

mp_loaders: 4
wandb: no
log_every: 10
evaluate_every: 10

class_label: 1

max_epochs: 1000
learning_rate: 0.001
batch_size: 1000

hidden_layer_dims: []
spline_order: 3
num_intervals: 5

lambda: 0.0
mu1: 1.0
mu2: 1.0

refine_grid_every: 200
update_grid_every: 5
stop_updating_grid_after: 50

load_from: logs/best_checkpoint_1210_mse=-0.0060.pt