









dataset_file: datasets.toy_2d
output_path: 'logs/'

mp_loaders: 4
wandb: no







max_epochs: 100
learning_rate: 0.01
batch_size: 128

hidden_layer_dims: [1]
spline_order: 3
num_intervals: 5

refine_grid_every: 200
update_grid_iterations: 100

load_from: null